apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns-pihole-release
  namespace: external-dns-system
spec:
  interval: 15m
  chart:
    spec:
      chart: external-dns
      version: 2.34.0
      sourceRef:
        kind: HelmRepository
        name: pihole-repo
