apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-double
provisioner: driver.longhorn.io
parameters:
  numberOfReplicas: "2"
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: Immediate
