apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-pvc
  namespace: media-system
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1500Gi
  storageClassName: longhorn-single
