apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin-release
  namespace: media-system
spec:
  interval: 15m
  chart:
    spec:
      chart: jellyfin
      version: 2.3.0
      sourceRef:
        kind: HelmRepository
        name: media-jellyfin-repo
  values:
    ingress:
      enabled: true
      hosts:
        - host: "jellyfin.home"
          paths:
            - path: "/"
              pathType: ImplementationSpecific
    persistence:
      media:
        existingClaim: media-pvc
        accessMode: ReadWriteMany

