apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx-release
  namespace: nginx-system
spec:
  interval: 15m
  chart:
    spec:
      chart: ingress-nginx
      version: 4.13.1
      sourceRef:
        kind: HelmRepository
        name: nginx-repo
  values:
    controller:
      ingressClassResource:
        name: ingress-nginx
        enabled: true
        default: true
